version: '3'

services:
  zm:
    build:
      context: ./context/zoneminder
      args:
        zm_version: '1.34'
        ffmpeg_version: 4.3-ubuntu1804
    image: zoneminder:1.34
    shm_size: '5gb'
    environment:
      TZ: 'Europe/Moscow'
      ZM_DB_HOST: db
      ZM_DB_NAME: zm
      ZM_DB_USER: zmuser
      ZM_DB_PASS: zmpass
    volumes:
      - ./.volumes/zm/logs:/var/log/zm
      - ./.volumes/zm/data:/var/cache/zoneminder
      - zm-run:/var/run/zm
      - zm-tmp:/tmp/zm
      # - ./config/zmeventnotification.ini:/etc/zm/zmeventnotification.ini:ro
      # - zmeventnotification-push:/var/lib/zmeventnotification/push

  apache:
    build:
      context: ./context/zoneminder/apache
      args:
        zm_version: '1.34'
    image: zoneminder:1.34-apache
    environment:
      TZ: 'Europe/Moscow'
      ZM_DB_HOST: db
      ZM_DB_NAME: zm
      ZM_DB_USER: zmuser
      ZM_DB_PASS: zmpass
    volumes:
      - ./.volumes/zm/logs:/var/log/zm
      - ./.volumes/zm/data:/var/cache/zoneminder
      - zm-run:/var/run/zm
      - zm-tmp:/tmp/zm
    ports:
      - '8080:80'

  zmaudit:
    image: zoneminder:1.34
    command: '/usr/bin/zmaudit.pl -c'
    environment:
      TZ: 'Europe/Moscow'
      ZM_DB_HOST: db
      ZM_DB_NAME: zm
      ZM_DB_USER: zmuser
      ZM_DB_PASS: zmpass
    volumes:
      - ./.volumes/zm/logs:/var/log/zm
      - ./.volumes/zm/data:/var/cache/zoneminder
      - zm-run:/var/run/zm
      - zm-tmp:/tmp/zm
      # - ./config/zmeventnotification.ini:/etc/zm/zmeventnotification.ini:ro

  db:
    image: mariadb:10.5
    environment:
      TZ: 'Europe/Moscow'
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'zmuser'
      MYSQL_PASSWORD: 'zmpass'
      MYSQL_DATABASE: 'zm'
    volumes:
      - db:/var/lib/mysql

volumes:
  zm-run:
  zm-tmp:
  zmeventnotification-push:
  db: